# Site
repository: alessiacaponera/alessiacaponera.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Alessia Caponera
title: Postdoctoral Researcher at École Polytechnique Fédérale de Lausanne
email: alessia.caponera@epfl.ch

# Social links
#twitter_username: sproogen
github_username:  alessiacaponera
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# pinterest_username:
# youtube_username:
# googleplus_username:


# About Section
about_title: About me
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    I am Postdoctoral Researcher at École Polytechnique Fédérale de Lausanne, in the research team of Prof. Victor Panaretos.

    I am mostly interested in space-time spherical random fields and related topics, such as spectral representations, spherical wavelets and needlets, functional data analysis on the sphere. I also appreciate teaching Statistics and any form of knowledge sharing.
    
    My complete curriculum vitae is available at [this link](/files/cv_Caponera.pdf). For more information about myself, you can also visit my [ResearchGate](https://www.researchgate.net/profile/Alessia-Caponera) and [Google Scholar](https://scholar.google.com/citations?user=stpPH0cAAAAJ&hl=en) profiles.
    
    [<mark>Download curriculum vitae</mark>](/files/cv_Caponera.pdf)

# Teaching Section
#teaching_title: Teaching @ Unimib
#teaching_content: |
#    The courses are paired with a website which includes the teaching material (slides, code, references, etc.).

#    **B.Sc. courses (corsi laurea triennale)**

#    - [**Statistics 1** (in Italian)](https://tommasorigon.github.io/StatI/), CdL in Scienze Statistiche ed Economiche, University of Milano-Bicocca. 
#    - [**R for the multivariate statistical analysis** (in Italian)](https://tommasorigon.github.io/introR/), CdL in Scienze Statistiche ed Economiche, University of Milano-Bicocca.
    
#    **B.Sc. & M.Sc. thesis (tesi triennale e magistrale)**

#    - [**Information page** (in Italian)](https://tommasorigon.github.io/files/tesi.html). Please read the information page if you are interested in working with me for your B.Sc. or M.Sc. thesis.

# Projects Section
projects_title: Academic positions

# Experience Section
#experience_title: Industry Experience

# Education Section
education_title: Education

# More Section
more_title: Publications
more_content: |

    **Articles in refereed journals**
    
    **Caponera, A.** (2021). SPHARMA approximations for stationary time series on the sphere. *Statistical Inference for Stochastic Processes*. [[DOI:10.1007/s11203-021-09244-6]](https://doi.org/10.1007/s11203-021-09244-6)
    
    **Caponera, A.**, Durastanti, C., Vidotto, A. (2021). LASSO estimation for spherical autoregressive processes. *Stochastic Processes and their Applications*, vol. 137, pp. 167-199. [[DOI:10.1016/j.spa.2021.03.009]](https://doi.org/10.1016/j.spa.2021.03.009)
    
    **Caponera, A.**, Marinucci, D. (2021). Asymptotics for spherical functional autoregressions. *Annals of Statistics*, vol. 49, no. 1, pp. 346-369. [[DOI:10.1214/20-AOS1959]](https://doi.org/10.1214/20-AOS1959)
    
    **Manuscripts under review and in preparation**
    
    **Caponera, A.**, Durastanti, C. (2021). Parametric estimation for functional autoregressive processes on the sphere. Submitted for publication. [[arXiv:2107.08900]](https://arxiv.org/pdf/2107.08900.pdf)
    
    **Refereed conference proceedings and book chapters**
    
    Spoto, F., **Caponera, A.**, Brutti, P. (2021). Spherical autoregressive change-point detection with applications. In: *Book of Short Papers SIS 2021*. ISBN: 9788891927361. [[Link]](https://it.pearson.com/content/dam/region-core/italy/pearson-italy/pdf/Docenti/Università/pearson-sis-book-2021-parte-2.pdf)
    
    **Caponera, A.**, Denti, F., Rigon, T., Sottosanti, A., Gelfand, A. (2018). Hierarchical Spatio-Temporal Modeling of Resting State fMRI Data. In: *Studies in Neural Data Science* (Canale, A., Durante, D., Paci, L., Scarpa, B., editors). [[Link]](https://www.springer.com/us/book/9783030000387) [[GitHub Repository]](https://github.com/tommasorigon/StartUpResearch)
    
    **Caponera, A.**, Werner, M. J. (2018). How robust is the skill score of probabilistic earthquake forecasts?. In: *Book of Short Papers SIS 2018*. ISBN: 9788891910233. [[Link]](https://it.pearson.com/content/dam/region-core/italy/pearson-italy/pdf/Docenti/ISTITUZIONI%20-%20HE%20-%20PDF%20-%20SIS%20V2.pdf)
    
# 
# More Section
#awards_title: Awards
#awards_content: |

#    **Academic awards**

#    - Best Ph.D. student in Statistics at Bocconi University in the Academic Year 2016/2017 (09/2017)

#    **Data competitions**

#    - Best objective prediction at [Stat under the Stars 4](https://www.unipa.it/dipartimenti/seas/sus4/), Palermo, Italy (06/2018)
#    - Winner of the Young-CLADAG data contest, Milan, Italy (09/2017)
#    - Winner of the [Bocconi summer school data competition](https://www.knowledge.unibocconi.it/notizia.php?idArt=1855), Como, Italy (07/2017)

#    **Travel award**

#    - Travel award (400£) for O'Bayes 2019 conference, Warwick, UK (06/2019)
#    - Travel award (accommodation) for the BNP12 conference, Oxford, UK (06/2019)
#    - ISBA travel award (250$) for ISBA 2018 world meeting, Edinburgh, UK (06/2018)
#    - ISBA travel award (700$) for the O'Bayes 2017 conference, Austin, Texas (12/2017)


# More Section
service_title: Service to profession
service_content: |

    **Referee service (alphabetical order)**

    Bernoulli; Electronic Journal of Statistics 
    
    **Positions in academic societies**

    - Elected member of the board (2018-2020) of the [young group (ySIS)](https://youngsis.github.io) of the Italian Statistical Society

    **Organization of scientific events**

    - Organizer of the y-SIS session *y-SIS: From methodology to applications* at [CMStatistics 2019](http://www.cmstatistics.org/CMStatistics2019/)
    - Member of the scientific committee of the [50th Scientific Meeting of the Italian Statistical Society (SIS2020)](http://meetings3.sis-statistica.org/index.php/sis2020/)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
