# Site
repository: alessiacaponera/alessiacaponera.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Alessia Caponera
title: Assistant Professor at University of Milano-Bicocca
email: alessia.caponera@unimib.it

# Social links
#twitter_username: sproogen
github_username:  alessiacaponera
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# pinterest_username:
# youtube_username:
# googleplus_username:


# About Section
about_title: About me
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    I am currently an Assistant Professor (Ricercatore SECS-S/01, Legge 240/10 tipo A) at the Department of Economics, Management and Statistics (DEMS), University of Milano-Bicocca.

    My research activity revolves around functional time series topics, with a special attention to spherical random fields. I also appreciate teaching Statistics and any form of knowledge sharing.
    
    My complete curriculum vitae is available at [this link](/files/cv_Caponera.pdf). For more information about myself, you can also visit my [ResearchGate](https://www.researchgate.net/profile/Alessia-Caponera) and [Google Scholar](https://scholar.google.com/citations?user=stpPH0cAAAAJ&hl=en) profiles.
    
    [<mark>Download curriculum vitae</mark>](/files/cv_Caponera.pdf)

# Projects Section
projects_title: Academic positions

# Experience Section
#experience_title: Industry Experience

# Education Section
education_title: Education

# More Section
more_title: Publications
more_content: |

    **Articles in refereed journals**

    **Caponera, A.** (2023+). Asymptotics for isotropic Hilbert-valued spherical random fields. *Bernoulli*, in press. [[arXiv]](https://arxiv.org/pdf/2212.02329.pdf)
    
    **Caponera, A.**, Fageot, J., Simeoni, M., Panaretos, V.M. (2022). Functional estimation of anisotropic covariance and autocovariance operators on the sphere. *Electronic Journal of Statistics*, vol. 16, no. 2, pp. 5080--5148. [[DOI:10.1214/22-EJS2064]](https://doi.org/10.1214/22-EJS2064) [[GitHub Repository]](https://github.com/matthieumeo/sphericov)
    
    **Caponera, A.**, Panaretos, V.M. (2022). On the rate of convergence for the autocorrelation operator in functional autoregression. *Statistics & Probability Letters*, vol. 189, p. 109575. [[DOI:10.1016/j.spl.2022.109575]](https://doi.org/10.1016/j.spl.2022.109575)
    
    **Caponera, A.**, Durastanti, C. (2022). Parametric estimation for functional autoregressive processes on the sphere. *Theory of Probability and Mathematical Statistics*, vol. 106, pp. 63--83. [[DOI:10.1090/tpms/1165]](https://doi.org/10.1090/tpms/1165)
    
    **Caponera, A.** (2021). SPHARMA approximations for stationary time series on the sphere. *Statistical Inference for Stochastic Processes*, vol. 24, pp. 609--634. [[DOI:10.1007/s11203-021-09244-6]](https://doi.org/10.1007/s11203-021-09244-6)
    
    **Caponera, A.**, Durastanti, C., Vidotto, A. (2021). LASSO estimation for spherical autoregressive processes. *Stochastic Processes and their Applications*, vol. 137, pp. 167--199. [[DOI:10.1016/j.spa.2021.03.009]](https://doi.org/10.1016/j.spa.2021.03.009)
    
    **Caponera, A.**, Marinucci, D. (2021). Asymptotics for spherical functional autoregressions. *Annals of Statistics*, vol. 49, no. 1, pp. 346--369. [[DOI:10.1214/20-AOS1959]](https://doi.org/10.1214/20-AOS1959)

    **Manuscripts under review and in preparation**
    
    **Caponera, A.**, Marinucci, D., Vidotto, A. (2023+). Multiscale CUSUM tests for time-dependent spherical random fields. Manuscript submitted for publication. [[arXiv]](https://arxiv.org/pdf/2305.01392.pdf)

    **Refereed conference proceedings and book chapters**
    
    Spoto, F., **Caponera, A.**, Brutti, P. (2022). Universal change point testing for dependent data. In: *Book of Short Papers SIS 2022*. ISBN 9788891932310. [[Link]](https://it.pearson.com/content/dam/region-core/italy/pearson-italy/pdf/Docenti/Università/Sis-2022-4c-low.pdf)
    
    Spoto, F., **Caponera, A.**, Brutti, P. (2021). Spherical autoregressive change-point detection with applications. In: *Book of Short Papers SIS 2021*. ISBN: 9788891927361. [[Link]](https://it.pearson.com/content/dam/region-core/italy/pearson-italy/pdf/Docenti/Università/pearson-sis-book-2021-parte-2.pdf)
    
    **Caponera, A.**, Denti, F., Rigon, T., Sottosanti, A., Gelfand, A. (2018). Hierarchical Spatio-Temporal Modeling of Resting State fMRI Data. In: *Studies in Neural Data Science* (Canale, A., Durante, D., Paci, L., Scarpa, B., editors). [[Link]](https://www.springer.com/us/book/9783030000387) [[GitHub Repository]](https://github.com/tommasorigon/StartUpResearch)
    
    **Caponera, A.**, Werner, M. J. (2018). How robust is the skill score of probabilistic earthquake forecasts?. In: *Book of Short Papers SIS 2018*. ISBN: 9788891910233. [[Link]](https://it.pearson.com/content/dam/region-core/italy/pearson-italy/pdf/Docenti/ISTITUZIONI%20-%20HE%20-%20PDF%20-%20SIS%20V2.pdf)
    

# More Section
awards_title: Awards
awards_content: |

    **Academic awards**

    - IMS New Researcher Travel Award to attend the 2022 IMS Annual Meeting (800USD)
    - ISBA Travel Award to attend the 2018 ISBA World Meeting (250USD) 


# More Section
service_title: Service to profession
service_content: |

    **Referee service**

    Electronic Journal of Statistics, Bernoulli, Computational Statistics and Data Analysis, Bayesian Analysis, Environmetrics 
    
    **Positions in academic societies**

    - Editor of Bernoulli Society Bulletin e-Briefs (from July 2023)
    - Member of the editorial board of [YoungStatS](https://youngstats.github.io) (since November 2022)
    - Elected member of the board of [Young SIS](https://youngsis.github.io) (2019-2021)
    - Member of the Italian Statistical Society (SIS), Institute of Mathematical Statistics (IMS), Bernoully Society

    **Organization of scientific events**
    
    - Member of the scientific committee of [EcoSta 2023](http://www.cmstatistics.org/EcoSta2023/) and organizer of the session *To stationarity and beyond: statistical inference for nonstationary data structures*
    - Organizer of the session *Probabilistic and statistical properties of sphere-cross-time random fields* at [Third Italian Meeting on Probability and Mathematical Statistics](https://site.unibo.it/probstat/en)
    - Organizer of the session *On the second-order dynamics of intricate functional data* at [EcoSta 2022](http://www.cmstatistics.org/EcoSta2022/)
    - Organizer of the y-SIS session *y-SIS: From methodology to applications* at [CMStatistics 2019](http://www.cmstatistics.org/CMStatistics2019/)
    - Member of the scientific committee of the [50th Scientific Meeting of the Italian Statistical Society (SIS2020)](http://meetings3.sis-statistica.org/index.php/sis2020/)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
